spring.application.name=bff

server.port=8080

#logging.level.org.springframework.security=DEBUG

rsa.public-key=file:keys/public.pem
rsa.private-key=file:keys/private.pem

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email